name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ubuntu packages
      run: sudo apt-get install autoconf-archive
    - name: autoreconf
      run: autoreconf -iv
    - name: configure
      run: mkdir build; cd build; ../configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
