name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Ubuntu packages
      run: sudo apt-get install autoconf-archive liblog4cxx-dev libi2c-dev gettext
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: autoreconf
      run: autoreconf -iv
    - name: configure
      run: mkdir build; cd build; ../configure
    - name: make -j6
      run: cd build; make V=1
    - name: make check
      run: cd build; make V=1 check
